[project]
name = "apsat-core"
version = "1.0.0"
description = "Core of Apsat"
readme = "README.md"
authors = [
    { name = "Deswatts", email = "Deswatts_Cre@outlook.com" }
]
requires-python = ">=3.14"
dependencies = [
    "deswatts-tools>=1.0.0",
    "requests"
]

[project.scripts]
apsat-core = "apsat_core:main"

[build-system]
requires = ["uv_build>=0.12.7,<0.13.0"]
build-backend = "uv_build"
