[project]
name = "apsat-core"
version = "1.0.2"
requires-python = ">=3.10"
dependencies = [
    "deswatts-tools>=1.0.0",
    "requests",
]
description = "Core of Apsat"
authors = [
    {name = "Deswatts", email = "Deswatts_Cre@outlook.com"}
]
maintainers = [
    {name = "Deswatts", email = "Deswatts_Cre@outlook.com"}
]
license = "GPL-3.0-or-later"
license-files = ["LICENSE"]
keywords = ["Apsat", "core"]
readme = "README.md"

[build-system]
requires = ["uv_build >= 0.9.2, <0.10.0"]
build-backend = "uv_build"
